# https://www.home-assistant.io/integrations/default_config/
default_config:

ffmpeg:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.teslemetry: debug
    tesla_fleet_api: debug
    teslemetry_stream: debug
