navigation_gps_request:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    latitude:
      required: true
      selector:
        text:
    longitude:
      required: true
      selector:
        text:
    order:
      required: false
      default: 1
      selector:
        number:
navigation_sc_request:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    id:
      required: true
      selector:
        number:
    order:
      required: false
      default: 1
      selector:
        number:
navigation_request:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    type:
      required: true
      selector:
        text:
    value:
      required: true
      selector:
        text:
    locale:
      required: false
      selector:
        text:
    timestamp_ms:
      required: false
      selector:
        text:
stream_fields:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    fields:
      required: true
      selector:
        object:
set_scheduled_charging:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    enable:
      required: true
      default: true
      selector:
        boolean:
    time:
      required: false
      selector:
        time:
set_scheduled_departure:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    enable:
      required: true
      default: true
      selector:
        boolean:
    time:
      required: false
      selector:
        time: