navigation_gps_request:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    latitude:
      required: true
      selector:
        text:
    longitude:
      required: true
      selector:
        text:
    order:
      required: false
      default: 1
      selector:
        number:
navigation_sc_request:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    id:
      required: true
      selector:
        number:
    order:
      required: false
      default: 1
      selector:
        number:
navigation_request:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: teslemetry
          entity:
            domain: button
    type:
      required: true
      selector:
        text:
    value:
      required: true
      selector:
        text:
    locale:
      required: false
      selector:
        text:
    timestamp_ms:
      required: false
      selector:
        text:

